include $(THEOS)/makefiles/common.mk

TWEAK_NAME = prettyrespringbackboardd
prettyrespringbackboardd_FILES = Tweak.xm $(wildcard *mm)
prettyrespringbackboardd_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk


